language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

script:
    - vendor/bin/tester tests -j 1 -s -p php -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    - travis_retry composer install --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
